name: CI - Build and Push to ECR

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: flask-hello-world
  GITOPS_BRANCH: gitops
  HELM_PATH: helm-chart

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # to push to gitops branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set IMAGE_TAG (timestamp)
        id: vars
        run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build, tag, and push Docker image to ECR
        id: build-image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Update Helm values in GitOps branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin ${{ env.GITOPS_BRANCH }}
          git checkout ${{ env.GITOPS_BRANCH }}

          sed -i "s|repository: .*|repository: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}|" ${{ env.HELM_PATH }}/values.yaml
          sed -i "s|tag: .*|tag: \"${{ env.IMAGE_TAG }}\"|g" ${{ env.HELM_PATH }}/values.yaml

          git add ${{ env.HELM_PATH }}/values.yaml
          git commit -m "Update image tag to $(date +%Y%m%d%H%M%S)"
          git push origin ${{ env.GITOPS_BRANCH }}
